name: Build, Push and Deploy Docker Image

on:
  push:
    branches: [ "unknown17" ]
  pull_request:
    branches: [ "unknown17" ]

env:
  SERVER_USERNAME: ubuntu
  SERVER_IP: 3.127.221.197
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy image to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "imtihon-6/lesson_ci_cd" ]; then
              git clone https://github.com/unknownn17/6-Oy-Imtihon.git imtihon-6/lesson_ci_cd
            fi
            cd imtihon-6/lesson_ci_cd/
            git pull origin unknown17
            sudo docker compose down
            sudo docker compose up --build -d
          script_stop: true
          timeout: 200s
